# Configuración WiFi
WIFI_SSID = 'INFINITUM4D7F'
WIFI_PASSWORD = 'WwtV7qAUo7'

# Configuración ThingSpeak MQTT
THINGSPEAK_MQTT_CLIENT_ID = b"OQsYGSsSAA4gCC8hAz0CHQ0"
THINGSPEAK_MQTT_USERNAME = b"OQsYGSsSAA4gCC8hAz0CHQ0"
THINGSPEAK_MQTT_PASSWORD = b"x7MfYsVlVDKWkxCAyAm7OIvG"
THINGSPEAK_CHANNEL_ID = b'2776160'

# Pines I2C
I2C_SCL_PIN = 5
I2C_SDA_PIN = 4

# Archivo CSV donde se guardarán los datos
CSV_FILENAME = "datos_climaticos.csv"
